version: '3.8'

services:
  nginx-service:
    image: nginx
    container_name: nginx_service
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/backend_task
    depends_on:
      - database
      - app

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend_app
    ports:
      - "9000:9000"
    extra_hosts:    # if we do not use windows then in order xdebug to work we need uncomment this parameter 
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www/backend_task
    depends_on:
      - database

  database:
    image: mysql:8.1
    container_name: database_service
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}